### ISSUE TITLE
Question about data in Tempose

### ISSUE THREAD

**Issue by a1742976730** [MagnusPetersenIbh/TemPose-BadmintonActionRecognition#1]
Can you tell me how the 2D/pose data is made please?

**Comment by MagnusPetersenIbh** [comment]
Absolutely, first the full badminton videos are retrieved from YouTube, where they are freely available. Then, the mmpose library is used to estimate the raw skeleton data from the videos. The skeleton data is preprocessed (filter out audience, etc.), and ground position is retrieved using an image2court homography. Lastly, using the annotations from https://ieeexplore.ieee.org/document/8354143, the individual action/stroke sequences are created.

**Comment by Va6lue** [comment]
Could you please tell me what the shapes of these four data are?
```
poses = pd.read_pickle('Data/2d_poses.pkl')
position = pd.read_pickle('Data/2d_positions.pkl')
shuttle = pd.read_pickle('Data/2d_shuttle-position.pkl')
labels = pd.read_pickle('Data/2d_labels.pkl')
```
I guess they are
poses: (N, T, num_people, 2J),
position: (N, T, num_people, 2),
shuttle: (N, T, 2),
labels: (N, num_classes),
and
T is the number of frames in a period of time,
J = 17 which means there are 17 skeleton points,
num_people=2 in a single badminton match,
num_classes=13 containing
top/bottom serve,
top/bottom forehand,
top/bottom backhand,
top/bottom smash,
top/bottom lob,
top/bottom react,
none.

Is my guessing correct?

**Comment by MagnusPetersenIbh** [comment]
Yes, exactly as you say. 
Except that the skeleton data also uses the bone-information (i.e. adjacent keypoint difference). That means 
Poses: (N,T,(2J + 2B))
Where the bones are the difference between connected joints. The function for bone calculation can be found in the DataUtils script.

**Comment by Va6lue** [comment]
Thanks for your replying.
I now know that the pose input shape is (b, n, t, d) where b is the batch size, n is the number of people, t is the number of frames and d is the number of features.
d = (2J+2B) when interpolation is disabled.
d = (2J+4B) when interpolation is enabled.
